Added CSS animations
negue/todo-overlay pull request #13
Opened 2020-10-06 05:13 UTC by SteveAndreou

Added simple fade-in css animation for new list items.

Made a few additional css changes to address the following:
- new fadeIn animation was conflicting with highlighting, added important to highlighting tag
- removed user selection from list items (stop click and drag highlighting on UI)

2020-10-06 15:15 UTC, negue commented on src/TaskList.svelte
> +    animation-name: fadeIn;
you could apply those values if `:not(.entry-done):not(.entry-highlight)` that way you don't need to apply `!important`

2020-10-06 15:16 UTC, negue requested changes
Only that one thing, otherwise thats perfect :)

Thank you!

2020-10-07 01:07 UTC, SteveAndreou commented
@negue thanks for the feedback, I've implemented your suggested changes.

2020-10-07 05:52 UTC, merged

2020-10-07 05:55 UTC, negue commented
Thank you for your first contribution!!

If you want and have an idea, feel free to add a "item remove" animation as well :)

@all-contributors please add @SteveAndreou for code

2020-10-07 05:56 UTC, negue commented
@all-contributors please add @SteveAndreou for code