Auto layout
negue/todo-overlay pull request #16
Opened 2020-10-07 08:22 UTC by SteveAndreou

This pull request addresses issues outlined in #12 

- Added auto layout as a query option.
- Updated documentation to reflect changes to the options.

2020-10-07 20:07 UTC, negue commented
oh awesome! let me check that (need to add github publish for each PR then its easier to test)

2020-10-07 20:39 UTC, negue requested changes
only the width but then this is LGTM 👍

2020-10-07 20:39 UTC, negue commented on src/TaskList.svelte
> +    width: fit-content;
I think the width can stay as it was (full width) only change the height settings 

then it'll only auto size in the height

2020-10-08 01:05 UTC, SteveAndreou commented
I've removed the width adjustment so that it will only scale vertically now.

2020-10-08 06:13 UTC, negue commented
LGTM 👍

2020-10-08 06:13 UTC, merged